steps:
  # Step 1: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devika', '.']

  # Step 2: Pushing the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/devika']

images:
  - 'gcr.io/$PROJECT_ID/devika'
